### ISSUE TITLE
locations in foreign code: level 2 is missing

### ISSUE THREAD

**Issue by pwbs** [ocaml/MPP-language-blender#20]
Latest version(s) of MPP print locations when using foreign code blocks, and it makes it easier to track errors. But the locations disappear after the foreign code has been evaluated. Evaluation of the foreign code should print source locations. However it's not as trivial as saying it: the format of the location depends on the final language, not the 1st nor the 2nd. But, it should be not too hard to make a version that works with CPP locations. This will probably bump MPP version to 0.2.x. as it will need a few changes in the interface.

**Comment by pw374** [comment]
addressed in https://github.com/ocaml/MPP-language-blender/commit/1eeec0c776a04ac0fdc048925479a8224bc6af2c
