### ISSUE TITLE
bash output adds new lines

### ISSUE THREAD

**Issue by smondet** [ocaml/MPP-language-blender#29]
The `bash` language output uses `echo`, so it adds new-lines.

```
{
cat <<EOF
hello {< printf "world" >}!
EOF
} | mpp -l bash | bash
```

gives

```
hello 
world!
```

Instead of `echo ...` it could use `printf '%s' ...` (it's POSIX `sh`).

**Comment by pw374** [comment]
I made a PR with `echo -n`, but `printf` works too. I haven't tested it to confirm it, but `echo -n` should be a bit faster than `printf`, since the latter has to parse its argument. (But, without testing it, who knows, it's an obscure world there, anything can happen.)

**Comment by pw374** [comment]
IDK if `echo -n` is `POSIX sh` or not. However, the shell being explicitly `bash`, it shouldn't cause any issue on that particular point.
